### ISSUE TITLE
Saving SWADL file throws exception intermittently

### ISSUE THREAD

**Issue by ystan-** [finos/symphony-wdk#100]
## Bug Report
Sometimes, when saving a SWADL file (usually after a long break while the WDK bot is still running), an exception is thrown when the WDK attempts to deploy the revised workflow. This doesn't actually impact the redeployment itself as it completes successfully after the exception is thrown, just that it confuses the reader with a false negative exception.

### Steps to Reproduce:
Save a SWADL file in a watched directory multiple times irregularly

### Expected Result:
```
2022-03-25 17:52:32.830  INFO 2857 --- [   scheduling-1] c.s.b.w.engine.camunda.CamundaEngine     : Deployed workflow 4aa729a6-ac21-11ec-a735-00155d0523ff meh
2022-03-25 17:52:32.830  INFO 2857 --- [   scheduling-1] audit-trail                              : event=deploy_workflow, deployment=4aa729a6-ac21-11ec-a735-00155d0523ff, deployment_name=meh, process_key=meh
```

### Actual Result:
```
2022-03-25 17:52:32.791 ERROR 2857 --- [   scheduling-1] c.s.b.w.c.WorkflowFolderWatcher          : Failed to update workflow for file change event meh.swadl.yaml

java.lang.NullPointerException: unhandled token type NOT_AVAILABLE
        at com.github.fge.jackson.NodeType.getNodeType(NodeType.java:144) ~[jackson-coreutils-2.0.jar!/:na]
        at com.github.fge.jsonschema.processors.data.SchemaContext.<init>(SchemaContext.java:50) ~[json-schema-validator-2.2.14.jar!/:na]
        at com.github.fge.jsonschema.processors.validation.InstanceValidator.process(InstanceValidator.java:103) ~[json-schema-validator-2.2.14.jar!/:na]
        at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:56) ~[json-schema-validator-2.2.14.jar!/:na]
        at com.github.fge.jsonschema.processors.validation.ValidationProcessor.process(ValidationProcessor.java:34) ~[json-schema-validator-2.2.14.jar!/:na]
        at com.github.fge.jsonschema.core.processing.ProcessingResult.of(ProcessingResult.java:79) ~[json-schema-core-1.2.14.jar!/:na]
        at com.github.fge.jsonschema.main.JsonSchemaImpl.doValidate(JsonSchemaImpl.java:77) ~[json-schema-validator-2.2.14.jar!/:na]
        at com.github.fge.jsonschema.main.JsonSchemaImpl.validate(JsonSchemaImpl.java:100) ~[json-schema-validator-2.2.14.jar!/:na]
        at com.github.fge.jsonschema.main.JsonSchemaImpl.validate(JsonSchemaImpl.java:110) ~[json-schema-validator-2.2.14.jar!/:na]
        at com.symphony.bdk.workflow.swadl.validator.SwadlValidator.validate(SwadlValidator.java:73) ~[classes!/:na]
        at com.symphony.bdk.workflow.swadl.validator.SwadlValidator.validateYaml(SwadlValidator.java:64) ~[classes!/:na]
        at com.symphony.bdk.workflow.swadl.SwadlParser.fromYaml(SwadlParser.java:53) ~[classes!/:na]
        at com.symphony.bdk.workflow.configuration.WorkflowFolderWatcher.addWorkflow(WorkflowFolderWatcher.java:138) ~[classes!/:na]
        at com.symphony.bdk.workflow.configuration.WorkflowFolderWatcher.handleFileEvent(WorkflowFolderWatcher.java:125) ~[classes!/:na]
        at com.symphony.bdk.workflow.configuration.WorkflowFolderWatcher.handleFileEventOrLogError(WorkflowFolderWatcher.java:104) ~[classes!/:na]
        at com.symphony.bdk.workflow.configuration.WorkflowFolderWatcher.watchFileEvents(WorkflowFolderWatcher.java:90) ~[classes!/:na]
        at com.symphony.bdk.workflow.configuration.WorkflowFolderWatcher.monitorWorkflowsFolder(WorkflowFolderWatcher.java:82) ~[classes!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.16.jar!/:5.3.16]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.16.jar!/:5.3.16]
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2022-03-25 17:52:32.830  INFO 2857 --- [   scheduling-1] c.s.b.w.engine.camunda.CamundaEngine     : Deployed workflow 4aa729a6-ac21-11ec-a735-00155d0523ff meh
2022-03-25 17:52:32.830  INFO 2857 --- [   scheduling-1] audit-trail                              : event=deploy_workflow, deployment=4aa729a6-ac21-11ec-a735-00155d0523ff, deployment_name=meh, process_key=meh
```

### Environment:
WDK 1.0.0

**Comment by ystxn** [comment]
Seems like this exception is a result of validating an empty string by the `jackson-coreutils` project, that has not been maintained for a very long time.

https://github.com/fge/jackson-coreutils/issues/14
